### ISSUE TITLE
Ошибка при добавлении новой заявки

### ISSUE THREAD

**Issue by Maksimovich1** [Maksimovich2/application#14]
![image](https://user-images.githubusercontent.com/25402494/179056023-ef21616b-3b77-41ee-9178-34a0d0a0d789.png)

1) Converter org.modelmapper.internal.converter.NumberConverter@6b8af64 failed to convert java.util.UUID to java.lang.Long.

1 error] with root cause

java.lang.NumberFormatException: For input string: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:na]
	at java.base/java.lang.Long.parseLong(Long.java:692) ~[na:na]
	at java.base/java.lang.Long.valueOf(Long.java:1144) ~[na:na]

**Comment by Maksimovich2** [comment]
done
